site_name: Discord Tickets
site_description: An open-source ticket management bot for Discord - a free alternative to the premium and white-label plans of other popular ticketing bots.
site_author: eartharoid
site_url: https://discordtickets.app
copyright: '&copy; 2021 Isaac Saunders'

repo_name: discord-tickets/bot
repo_url: https://github.com/discord-tickets/bot
edit_uri: https://github.com/discord-tickets/docs/blob/master/docs/

extra_css:
    - stylesheets/extra.css
# extra_javascript:

theme:
  name: material
  language: en
  custom_dir: overrides/
  palette:
    - scheme: default
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: octicons/moon-16
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - announce.dismiss
    - navigation.instant
    - navigation.top
    # - navigation.expand
    # - navigation.sections
    - navigation.tracking
    # - navigation.tabs
    - navigation.indexes
    - toc.integrate
  logo: /img/logo.png
  favicon: /favicon.ico
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/discord-tickets
    - icon: fontawesome/brands/discord
      link: https://lnk.earth/discord
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DiscordTickets

plugins:
  - search
  - git-revision-date-localized
  - redirects:
        redirect_maps:
            'sponsor.md': 'https://github.com/discord-tickets/bot/?sponsor=1'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      repo_url_shortener: true
      user: discord-tickets
      # repo: bot
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify