site_name: Discord Tickets
site_description: An open-source ticket management bot for Discord - a free alternative to the premium and white-label plans of other popular ticketing bots.
site_author: eartharoid
site_url: https://discordtickets.app
copyright: "&copy; 2022 Isaac Saunders"

repo_name: discord-tickets/bot
repo_url: https://github.com/discord-tickets/bot
edit_uri: https://github.com/discord-tickets/docs/blob/master/docs/

extra_css:
  - stylesheets/extra.css
# extra_javascript:

theme:
  name: material
  language: en
  custom_dir: overrides/
  palette:
    - scheme: default
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: octicons/moon-16
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: img/logo.png
  favicon: favicon.ico
  icon:
    repo: fontawesome/brands/github

plugins:
  - search: {}
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: true
  - redirects:
      redirect_maps:
        "sponsor.md": "https://github.com/discord-tickets/bot/?sponsor=1"

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - md_in_html
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      repo_url_shortener: true
      user: discord-tickets
      # repo: bot
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }

nav:
  - Home: index.md
  - Documentation:
    - Getting started: getting-started.md
    - Features:
       - Features: features/index.md
       - Commands: features/commands.md
    - FAQs: faqs.md
    - Managed hosting: managed.md
    - Self hosting:
      - Self hosting: self-hosting/index.md
      - Creating your Discord application: self-hosting/discord-application.md
      - Installation:
        - Installation: self-hosting/installation/index.md
        - Docker:
          - Docker: self-hosting/installation/docker/index.md
          - Environment variables: self-hosting/installation/docker/env.md
        - Standalone:
          - Standalone: self-hosting/installation/standalone/index.md
          - Environment variables: self-hosting/installation/standalone/env.md
          - Additional help: self-hosting/installation/standalone/additional-help.md
        - Pterodactyl:
          - Pterodactyl: self-hosting/installation/pterodactyl/index.md
          - Environment variables: self-hosting/installation/pterodactyl/env.md
        - PebbleHost:
          - PebbleHost: self-hosting/installation/pebblehost/index.md
          - Environment variables: self-hosting/installation/pebblehost/env.md
      - Reverse proxy setup: self-hosting/reverse-proxy.md
      - Further configuration: self-hosting/configuration.md
      - Portal installation: self-hosting/portal.md
      - Updating: self-hosting/updating.md
    - Configuration:
      - Configuration: configuration/index.md
      - General settings: configuration/general.md
      - Categories:
        - Categories: configuration/categories/index.md
        - Category questions: configuration/categories/questions.md
      - Panels: configuration/panels.md
      - Tags: configuration/tags.md
    - Troubleshooting: troubleshooting.md
    - Terms of service: terms.md
  - Blog: https://blog.discordtickets.app
  - Changelogs: changelogs/index.md
  - Privacy: privacy.md