# Project information
site_name: Discord Tickets
site_description: An open-source ticket management bot for Discord - a free alternative to the premium and white-label plans of other popular ticketing bots.
site_author: eartharoid
site_url: https://discordtickets.app

# Repository
repo_name: discord-tickets/bot
repo_url: https://github.com/discord-tickets/bot
edit_uri: https://github.com/discord-tickets/docs/blob/master/docs/

# Copyright
copyright: '&copy; 2021 Isaac Saunders'

# Configuration
extra_css:
    - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
  - javascripts/home.js


theme:
  name: material
  language: en
  custom_dir: overrides/
  # palette:
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     toggle:
  #       icon: material/weather-sunny
  #       name: Switch to dark mode
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     toggle:
  #       icon: material/weather-night
  #       name: Switch to light mode
  palette:
    scheme: slate # scheme: preference
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - toc.integrate
  logo: /img/logo.png
  favicon: /img/favicon.ico

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/discord-tickets
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DiscordTickets

plugins:
  - search
  - git-revision-date-localized:
      # type: timeago
  # - awesome-pages

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify

nav:
  - Home: index.md
  - Try Discord Tickets: try.md
  - Getting started: getting-started.md
  - Installation: installation.md
  - Configuration:
    - Configuration: configuration/index.md
  - Fully managed hosting: hosting.md
  - Updating: updating.md
  - Changelog: changelog.md